# Menggunakan base image Python
FROM python:3.9

# Menyeting working directory
WORKDIR /app

# Menyalin requirements dan menginstall dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Menyalin semua kode ke dalam container
COPY . .

# Menjalankan aplikasi
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3001"]
